import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Stupid Bird",
  description: "Generated by tk",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative mx-auto border-2 select-none cursor-pointer bg-[#70c5ce] w-[100vw] md:w-[600px] h-[100vh] overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
