import "./globals.css";
import { HelperProvider } from "@/components/providers/helper-provider";
import { Playpen_Sans_Thai } from "next/font/google";
import { FullLoadingProvider } from "@/components/providers/full-loading-provider";

const playpenSans = Playpen_Sans_Thai({
  subsets: ["latin"],
  variable: "--font-playpen-sans",
});

export const metadata = {
  title: "Stupid Bird",
  description: "Generated by tk",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="th" className={playpenSans.variable}>
      <body>
        <div
          className={`relative mx-auto select-none bg-[#70c5ce] w-[100vw] md:w-[600px] h-[100vh] overflow-hidden`}
        >
          <FullLoadingProvider>
            <HelperProvider>{children}</HelperProvider>
          </FullLoadingProvider>
        </div>
      </body>
    </html>
  );
}
